### ISSUE TITLE
About how to make a mask file in a dataset

### ISSUE THREAD

**Issue by chuchu1204** [Depanshu-Sani/SICKLE#2]
I have mapped vector polygons of fields using QGIS, but I don't know how to convert the vectors to raster images with multiple labeled bands, and would be grateful if you could tell me how to make them!

**Comment by sandeep-ccss** [comment]
In QGIS, you can use the rasterise tool in (Raster > Conversion > Rasterise) to rasterise each attribute individually. Then, you can use the merge raster tool in (Raster > Miscellaneous > Merge) to combine all the individual raster layers into a multiband raster layer.

**Comment by chuchu1204** [comment]
I appreciate your answer, I already know how to do it!
